
GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Order pizza"
}

###

DELETE http://localhost:3001/todo/delete/65aaaef6a4fa1fd0803cce68


###

PUT http://localhost:3001/todo/complete/65aab88cbbce827f2890d8f6
